### ISSUE TITLE
what the difference between by the official geolocation plugin

### ISSUE THREAD

**Issue by bau720123** [louisbl/cordova-plugin-gpslocation#1]
hi @louisbl 
what the difference between by the official geolocation plugin
http://plugins.cordova.io/#/package/org.apache.cordova.geolocation

**Comment by louisbl** [comment]
The [cordova geolocation plugin](http://plugins.cordova.io/#/package/org.apache.cordova.geolocation) does not use Android code anymore : https://issues.apache.org/jira/browse/CB-5977. It relies on the geolocation capability of the WebView.
This plugin use the [Android location API](http://developer.android.com/reference/android/location/package-summary.html) and force the use of the GPS provider.

In some case it's more convenient and/or more accurate to have only the GPS provider and not rely on network signals.

FYI there is also a [locations services plugin](http://plugins.cordova.io/#/package/fr.louisbl.cordova.locationservices) which use the [Google Location Services API](http://developer.android.com/reference/com/google/android/gms/location/package-summary.html).
